/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormCalendarRange: typeof import('./../components/form-calendar-range/index.vue')['default']
    FormDatePicker: typeof import('./../components/form-date-picker/index.vue')['default']
    FormPicker: typeof import('./../components/form-picker/index.vue')['default']
    IRiLockFill: typeof import('~icons/ri/lock-fill')['default']
    IRiUserFill: typeof import('~icons/ri/user-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./../components/safe-area/index.vue')['default']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanToast: typeof import('vant/es')['Toast']
  }
}
